require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Metrics/MethodLength:
  CountComments: false
  Max: 30
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
