require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
